#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 138
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  anon_sym_LBRACE_PERCENT = 1,
  aux_sym_startfor_token1 = 2,
  aux_sym_startfor_token2 = 3,
  anon_sym_PERCENT_RBRACE = 4,
  aux_sym_endfor_token1 = 5,
  aux_sym_startif_token1 = 6,
  aux_sym_endif_token1 = 7,
  aux_sym_startraw_token1 = 8,
  aux_sym_endraw_token1 = 9,
  aux_sym_extends_statement_token1 = 10,
  aux_sym_startblock_token1 = 11,
  aux_sym_endblock_token1 = 12,
  anon_sym_LBRACE_LBRACE = 13,
  anon_sym_RBRACE_RBRACE = 14,
  anon_sym_CARET_POUND = 15,
  anon_sym_POUND_POUND = 16,
  anon_sym_LBRACE_POUND = 17,
  anon_sym_POUND_RBRACE = 18,
  aux_sym__text_token1 = 19,
  anon_sym_LBRACE = 20,
  anon_sym_RBRACE = 21,
  anon_sym_POUND = 22,
  anon_sym_PERCENT = 23,
  sym_source_file = 24,
  sym__block = 25,
  sym_for_statement = 26,
  sym_startfor = 27,
  sym_endfor = 28,
  sym_if_statement = 29,
  sym_startif = 30,
  sym_endif = 31,
  sym_raw_statement = 32,
  sym_startraw = 33,
  sym_endraw = 34,
  sym_extends_statement = 35,
  sym_block_statement = 36,
  sym_startblock = 37,
  sym_endblock = 38,
  sym_expression = 39,
  sym__statement = 40,
  sym_line_statement = 41,
  sym_comment = 42,
  sym__text = 43,
  sym__rawtext = 44,
  sym_jinja_stuff = 45,
  sym_text = 46,
  sym_rawtext = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_jinja_stuff_repeat1 = 49,
  aux_sym_rawtext_repeat1 = 50,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [aux_sym_startfor_token1] = "startfor_token1",
  [aux_sym_startfor_token2] = "startfor_token2",
  [anon_sym_PERCENT_RBRACE] = "%}",
  [aux_sym_endfor_token1] = "endfor_token1",
  [aux_sym_startif_token1] = "startif_token1",
  [aux_sym_endif_token1] = "endif_token1",
  [aux_sym_startraw_token1] = "startraw_token1",
  [aux_sym_endraw_token1] = "endraw_token1",
  [aux_sym_extends_statement_token1] = "extends_statement_token1",
  [aux_sym_startblock_token1] = "startblock_token1",
  [aux_sym_endblock_token1] = "endblock_token1",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_CARET_POUND] = "^#",
  [anon_sym_POUND_POUND] = "##",
  [anon_sym_LBRACE_POUND] = "{#",
  [anon_sym_POUND_RBRACE] = "#}",
  [aux_sym__text_token1] = "_text_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_POUND] = "#",
  [anon_sym_PERCENT] = "%",
  [sym_source_file] = "source_file",
  [sym__block] = "_block",
  [sym_for_statement] = "for_statement",
  [sym_startfor] = "startfor",
  [sym_endfor] = "endfor",
  [sym_if_statement] = "if_statement",
  [sym_startif] = "startif",
  [sym_endif] = "endif",
  [sym_raw_statement] = "raw_statement",
  [sym_startraw] = "startraw",
  [sym_endraw] = "endraw",
  [sym_extends_statement] = "extends_statement",
  [sym_block_statement] = "block_statement",
  [sym_startblock] = "startblock",
  [sym_endblock] = "endblock",
  [sym_expression] = "expression",
  [sym__statement] = "_statement",
  [sym_line_statement] = "line_statement",
  [sym_comment] = "comment",
  [sym__text] = "_text",
  [sym__rawtext] = "_rawtext",
  [sym_jinja_stuff] = "jinja_stuff",
  [sym_text] = "text",
  [sym_rawtext] = "rawtext",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_jinja_stuff_repeat1] = "jinja_stuff_repeat1",
  [aux_sym_rawtext_repeat1] = "rawtext_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [aux_sym_startfor_token1] = aux_sym_startfor_token1,
  [aux_sym_startfor_token2] = aux_sym_startfor_token2,
  [anon_sym_PERCENT_RBRACE] = anon_sym_PERCENT_RBRACE,
  [aux_sym_endfor_token1] = aux_sym_endfor_token1,
  [aux_sym_startif_token1] = aux_sym_startif_token1,
  [aux_sym_endif_token1] = aux_sym_endif_token1,
  [aux_sym_startraw_token1] = aux_sym_startraw_token1,
  [aux_sym_endraw_token1] = aux_sym_endraw_token1,
  [aux_sym_extends_statement_token1] = aux_sym_extends_statement_token1,
  [aux_sym_startblock_token1] = aux_sym_startblock_token1,
  [aux_sym_endblock_token1] = aux_sym_endblock_token1,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_CARET_POUND] = anon_sym_CARET_POUND,
  [anon_sym_POUND_POUND] = anon_sym_POUND_POUND,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [anon_sym_POUND_RBRACE] = anon_sym_POUND_RBRACE,
  [aux_sym__text_token1] = aux_sym__text_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_source_file] = sym_source_file,
  [sym__block] = sym__block,
  [sym_for_statement] = sym_for_statement,
  [sym_startfor] = sym_startfor,
  [sym_endfor] = sym_endfor,
  [sym_if_statement] = sym_if_statement,
  [sym_startif] = sym_startif,
  [sym_endif] = sym_endif,
  [sym_raw_statement] = sym_raw_statement,
  [sym_startraw] = sym_startraw,
  [sym_endraw] = sym_endraw,
  [sym_extends_statement] = sym_extends_statement,
  [sym_block_statement] = sym_block_statement,
  [sym_startblock] = sym_startblock,
  [sym_endblock] = sym_endblock,
  [sym_expression] = sym_expression,
  [sym__statement] = sym__statement,
  [sym_line_statement] = sym_line_statement,
  [sym_comment] = sym_comment,
  [sym__text] = sym__text,
  [sym__rawtext] = sym__rawtext,
  [sym_jinja_stuff] = sym_jinja_stuff,
  [sym_text] = sym_text,
  [sym_rawtext] = sym_rawtext,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_jinja_stuff_repeat1] = aux_sym_jinja_stuff_repeat1,
  [aux_sym_rawtext_repeat1] = aux_sym_rawtext_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_startfor_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_startfor_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_endfor_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_startif_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_endif_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_startraw_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_endraw_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_extends_statement_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_startblock_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_endblock_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_for_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_startfor] = {
    .visible = true,
    .named = true,
  },
  [sym_endfor] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_startif] = {
    .visible = true,
    .named = true,
  },
  [sym_endif] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_startraw] = {
    .visible = true,
    .named = true,
  },
  [sym_endraw] = {
    .visible = true,
    .named = true,
  },
  [sym_extends_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_startblock] = {
    .visible = true,
    .named = true,
  },
  [sym_endblock] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_line_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__rawtext] = {
    .visible = false,
    .named = true,
  },
  [sym_jinja_stuff] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_rawtext] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_jinja_stuff_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rawtext_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[1][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(34);
      if (lookahead == '#') ADVANCE(69);
      if (lookahead == '%') ADVANCE(72);
      if (lookahead == '^') ADVANCE(2);
      if (lookahead == 'b') ADVANCE(18);
      if (lookahead == 'e') ADVANCE(20);
      if (lookahead == 'f') ADVANCE(22);
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(6);
      if (lookahead == '{') ADVANCE(63);
      if (lookahead == '}') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(69);
      if (lookahead == '%') ADVANCE(72);
      if (lookahead == '^') ADVANCE(2);
      if (lookahead == 'b') ADVANCE(18);
      if (lookahead == 'e') ADVANCE(20);
      if (lookahead == 'f') ADVANCE(22);
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(6);
      if (lookahead == '{') ADVANCE(63);
      if (lookahead == '}') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(54);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '%') ADVANCE(71);
      if (lookahead == '{') ADVANCE(62);
      if (lookahead == '}') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '%') ADVANCE(71);
      if (lookahead == '{') ADVANCE(64);
      if (lookahead == '}') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(70);
      if (lookahead == '%') ADVANCE(72);
      if (lookahead == '{') ADVANCE(63);
      if (lookahead == '}') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(19);
      if (lookahead == 'f') ADVANCE(24);
      if (lookahead == 'i') ADVANCE(15);
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(46);
      END_STATE();
    case 16:
      if (lookahead == 'k') ADVANCE(50);
      END_STATE();
    case 17:
      if (lookahead == 'k') ADVANCE(51);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(11);
      if (lookahead == 'x') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(49);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 30:
      if (lookahead == 'w') ADVANCE(47);
      END_STATE();
    case 31:
      if (lookahead == 'w') ADVANCE(48);
      END_STATE();
    case 32:
      if (eof) ADVANCE(34);
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '%') ADVANCE(71);
      if (lookahead == '^') ADVANCE(58);
      if (lookahead == '{') ADVANCE(63);
      if (lookahead == '}') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 33:
      if (eof) ADVANCE(34);
      if (lookahead == '#') ADVANCE(68);
      if (lookahead == '%') ADVANCE(71);
      if (lookahead == '^') ADVANCE(58);
      if (lookahead == '{') ADVANCE(63);
      if (lookahead == '}') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_startfor_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_startfor_token1);
      if (lookahead == '+') ADVANCE(41);
      if (lookahead == '-') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_startfor_token1);
      if (lookahead == '+') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(61);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_startfor_token1);
      if (lookahead == '+') ADVANCE(36);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_startfor_token1);
      if (lookahead == '+') ADVANCE(36);
      if (lookahead == '-') ADVANCE(39);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_startfor_token1);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(61);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_startfor_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_endfor_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_startif_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_endif_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_startraw_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_endraw_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_extends_statement_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_startblock_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_endblock_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_CARET_POUND);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_POUND_POUND);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_POUND_RBRACE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == '#') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(61);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == '^') ADVANCE(58);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(61);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(56);
      if (lookahead == '%') ADVANCE(35);
      if (lookahead == '{') ADVANCE(52);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '%') ADVANCE(35);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '}') ADVANCE(53);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(55);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(55);
      if (lookahead == '}') ADVANCE(57);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '}') ADVANCE(57);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '}') ADVANCE(43);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 32},
  [2] = {.lex_state = 32},
  [3] = {.lex_state = 32},
  [4] = {.lex_state = 32},
  [5] = {.lex_state = 32},
  [6] = {.lex_state = 32},
  [7] = {.lex_state = 32},
  [8] = {.lex_state = 32},
  [9] = {.lex_state = 32},
  [10] = {.lex_state = 32},
  [11] = {.lex_state = 32},
  [12] = {.lex_state = 32},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 33},
  [21] = {.lex_state = 33},
  [22] = {.lex_state = 33},
  [23] = {.lex_state = 33},
  [24] = {.lex_state = 32},
  [25] = {.lex_state = 32},
  [26] = {.lex_state = 32},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 33},
  [29] = {.lex_state = 32},
  [30] = {.lex_state = 32},
  [31] = {.lex_state = 33},
  [32] = {.lex_state = 32},
  [33] = {.lex_state = 32},
  [34] = {.lex_state = 32},
  [35] = {.lex_state = 32},
  [36] = {.lex_state = 32},
  [37] = {.lex_state = 32},
  [38] = {.lex_state = 32},
  [39] = {.lex_state = 32},
  [40] = {.lex_state = 32},
  [41] = {.lex_state = 32},
  [42] = {.lex_state = 32},
  [43] = {.lex_state = 32},
  [44] = {.lex_state = 32},
  [45] = {.lex_state = 32},
  [46] = {.lex_state = 32},
  [47] = {.lex_state = 32},
  [48] = {.lex_state = 32},
  [49] = {.lex_state = 32},
  [50] = {.lex_state = 32},
  [51] = {.lex_state = 32},
  [52] = {.lex_state = 32},
  [53] = {.lex_state = 32},
  [54] = {.lex_state = 32},
  [55] = {.lex_state = 32},
  [56] = {.lex_state = 32},
  [57] = {.lex_state = 32},
  [58] = {.lex_state = 32},
  [59] = {.lex_state = 32},
  [60] = {.lex_state = 32},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 37},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 37},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 40},
  [90] = {.lex_state = 40},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 40},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 40},
  [99] = {.lex_state = 40},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 40},
  [104] = {.lex_state = 40},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 40},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 40},
  [109] = {.lex_state = 40},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 40},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 40},
  [117] = {.lex_state = 40},
  [118] = {.lex_state = 40},
  [119] = {.lex_state = 40},
  [120] = {.lex_state = 40},
  [121] = {.lex_state = 40},
  [122] = {.lex_state = 40},
  [123] = {.lex_state = 40},
  [124] = {.lex_state = 40},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 40},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 40},
  [132] = {.lex_state = 40},
  [133] = {.lex_state = 40},
  [134] = {.lex_state = 40},
  [135] = {.lex_state = 40},
  [136] = {.lex_state = 40},
  [137] = {.lex_state = 40},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
    [aux_sym_startfor_token2] = ACTIONS(1),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(1),
    [aux_sym_endfor_token1] = ACTIONS(1),
    [aux_sym_startif_token1] = ACTIONS(1),
    [aux_sym_endif_token1] = ACTIONS(1),
    [aux_sym_startraw_token1] = ACTIONS(1),
    [aux_sym_endraw_token1] = ACTIONS(1),
    [aux_sym_extends_statement_token1] = ACTIONS(1),
    [aux_sym_startblock_token1] = ACTIONS(1),
    [aux_sym_endblock_token1] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_CARET_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_POUND_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(107),
    [sym__block] = STATE(7),
    [sym_for_statement] = STATE(7),
    [sym_startfor] = STATE(4),
    [sym_if_statement] = STATE(7),
    [sym_startif] = STATE(5),
    [sym_raw_statement] = STATE(7),
    [sym_startraw] = STATE(16),
    [sym_extends_statement] = STATE(7),
    [sym_block_statement] = STATE(7),
    [sym_startblock] = STATE(70),
    [sym_expression] = STATE(7),
    [sym__statement] = STATE(7),
    [sym_line_statement] = STATE(7),
    [sym_comment] = STATE(7),
    [sym__text] = STATE(24),
    [sym_text] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_jinja_stuff_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_CARET_POUND] = ACTIONS(9),
    [anon_sym_LBRACE_POUND] = ACTIONS(11),
    [aux_sym__text_token1] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
  },
  [2] = {
    [sym__block] = STATE(12),
    [sym_for_statement] = STATE(12),
    [sym_startfor] = STATE(8),
    [sym_if_statement] = STATE(12),
    [sym_startif] = STATE(6),
    [sym_endif] = STATE(52),
    [sym_raw_statement] = STATE(12),
    [sym_startraw] = STATE(13),
    [sym_extends_statement] = STATE(12),
    [sym_block_statement] = STATE(12),
    [sym_startblock] = STATE(72),
    [sym_expression] = STATE(12),
    [sym__statement] = STATE(12),
    [sym_line_statement] = STATE(12),
    [sym_comment] = STATE(12),
    [sym__text] = STATE(26),
    [sym_text] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_jinja_stuff_repeat1] = STATE(26),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(15),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [3] = {
    [sym__block] = STATE(12),
    [sym_for_statement] = STATE(12),
    [sym_startfor] = STATE(8),
    [sym_endfor] = STATE(47),
    [sym_if_statement] = STATE(12),
    [sym_startif] = STATE(6),
    [sym_raw_statement] = STATE(12),
    [sym_startraw] = STATE(13),
    [sym_extends_statement] = STATE(12),
    [sym_block_statement] = STATE(12),
    [sym_startblock] = STATE(72),
    [sym_expression] = STATE(12),
    [sym__statement] = STATE(12),
    [sym_line_statement] = STATE(12),
    [sym_comment] = STATE(12),
    [sym__text] = STATE(26),
    [sym_text] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_jinja_stuff_repeat1] = STATE(26),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [4] = {
    [sym__block] = STATE(10),
    [sym_for_statement] = STATE(10),
    [sym_startfor] = STATE(8),
    [sym_endfor] = STATE(37),
    [sym_if_statement] = STATE(10),
    [sym_startif] = STATE(6),
    [sym_raw_statement] = STATE(10),
    [sym_startraw] = STATE(13),
    [sym_extends_statement] = STATE(10),
    [sym_block_statement] = STATE(10),
    [sym_startblock] = STATE(72),
    [sym_expression] = STATE(10),
    [sym__statement] = STATE(10),
    [sym_line_statement] = STATE(10),
    [sym_comment] = STATE(10),
    [sym__text] = STATE(26),
    [sym_text] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [aux_sym_jinja_stuff_repeat1] = STATE(26),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [5] = {
    [sym__block] = STATE(11),
    [sym_for_statement] = STATE(11),
    [sym_startfor] = STATE(8),
    [sym_if_statement] = STATE(11),
    [sym_startif] = STATE(6),
    [sym_endif] = STATE(40),
    [sym_raw_statement] = STATE(11),
    [sym_startraw] = STATE(13),
    [sym_extends_statement] = STATE(11),
    [sym_block_statement] = STATE(11),
    [sym_startblock] = STATE(72),
    [sym_expression] = STATE(11),
    [sym__statement] = STATE(11),
    [sym_line_statement] = STATE(11),
    [sym_comment] = STATE(11),
    [sym__text] = STATE(26),
    [sym_text] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_jinja_stuff_repeat1] = STATE(26),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [6] = {
    [sym__block] = STATE(2),
    [sym_for_statement] = STATE(2),
    [sym_startfor] = STATE(8),
    [sym_if_statement] = STATE(2),
    [sym_startif] = STATE(6),
    [sym_endif] = STATE(49),
    [sym_raw_statement] = STATE(2),
    [sym_startraw] = STATE(13),
    [sym_extends_statement] = STATE(2),
    [sym_block_statement] = STATE(2),
    [sym_startblock] = STATE(72),
    [sym_expression] = STATE(2),
    [sym__statement] = STATE(2),
    [sym_line_statement] = STATE(2),
    [sym_comment] = STATE(2),
    [sym__text] = STATE(26),
    [sym_text] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_jinja_stuff_repeat1] = STATE(26),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(15),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [7] = {
    [sym__block] = STATE(9),
    [sym_for_statement] = STATE(9),
    [sym_startfor] = STATE(4),
    [sym_if_statement] = STATE(9),
    [sym_startif] = STATE(5),
    [sym_raw_statement] = STATE(9),
    [sym_startraw] = STATE(16),
    [sym_extends_statement] = STATE(9),
    [sym_block_statement] = STATE(9),
    [sym_startblock] = STATE(70),
    [sym_expression] = STATE(9),
    [sym__statement] = STATE(9),
    [sym_line_statement] = STATE(9),
    [sym_comment] = STATE(9),
    [sym__text] = STATE(24),
    [sym_text] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_jinja_stuff_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_CARET_POUND] = ACTIONS(9),
    [anon_sym_LBRACE_POUND] = ACTIONS(11),
    [aux_sym__text_token1] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
  },
  [8] = {
    [sym__block] = STATE(3),
    [sym_for_statement] = STATE(3),
    [sym_startfor] = STATE(8),
    [sym_endfor] = STATE(50),
    [sym_if_statement] = STATE(3),
    [sym_startif] = STATE(6),
    [sym_raw_statement] = STATE(3),
    [sym_startraw] = STATE(13),
    [sym_extends_statement] = STATE(3),
    [sym_block_statement] = STATE(3),
    [sym_startblock] = STATE(72),
    [sym_expression] = STATE(3),
    [sym__statement] = STATE(3),
    [sym_line_statement] = STATE(3),
    [sym_comment] = STATE(3),
    [sym__text] = STATE(26),
    [sym_text] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_jinja_stuff_repeat1] = STATE(26),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [9] = {
    [sym__block] = STATE(9),
    [sym_for_statement] = STATE(9),
    [sym_startfor] = STATE(4),
    [sym_if_statement] = STATE(9),
    [sym_startif] = STATE(5),
    [sym_raw_statement] = STATE(9),
    [sym_startraw] = STATE(16),
    [sym_extends_statement] = STATE(9),
    [sym_block_statement] = STATE(9),
    [sym_startblock] = STATE(70),
    [sym_expression] = STATE(9),
    [sym__statement] = STATE(9),
    [sym_line_statement] = STATE(9),
    [sym_comment] = STATE(9),
    [sym__text] = STATE(24),
    [sym_text] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_jinja_stuff_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(33),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(35),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(38),
    [anon_sym_CARET_POUND] = ACTIONS(41),
    [anon_sym_LBRACE_POUND] = ACTIONS(44),
    [aux_sym__text_token1] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(47),
    [anon_sym_RBRACE] = ACTIONS(47),
    [anon_sym_POUND] = ACTIONS(47),
    [anon_sym_PERCENT] = ACTIONS(47),
  },
  [10] = {
    [sym__block] = STATE(12),
    [sym_for_statement] = STATE(12),
    [sym_startfor] = STATE(8),
    [sym_endfor] = STATE(39),
    [sym_if_statement] = STATE(12),
    [sym_startif] = STATE(6),
    [sym_raw_statement] = STATE(12),
    [sym_startraw] = STATE(13),
    [sym_extends_statement] = STATE(12),
    [sym_block_statement] = STATE(12),
    [sym_startblock] = STATE(72),
    [sym_expression] = STATE(12),
    [sym__statement] = STATE(12),
    [sym_line_statement] = STATE(12),
    [sym_comment] = STATE(12),
    [sym__text] = STATE(26),
    [sym_text] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_jinja_stuff_repeat1] = STATE(26),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [11] = {
    [sym__block] = STATE(12),
    [sym_for_statement] = STATE(12),
    [sym_startfor] = STATE(8),
    [sym_if_statement] = STATE(12),
    [sym_startif] = STATE(6),
    [sym_endif] = STATE(41),
    [sym_raw_statement] = STATE(12),
    [sym_startraw] = STATE(13),
    [sym_extends_statement] = STATE(12),
    [sym_block_statement] = STATE(12),
    [sym_startblock] = STATE(72),
    [sym_expression] = STATE(12),
    [sym__statement] = STATE(12),
    [sym_line_statement] = STATE(12),
    [sym_comment] = STATE(12),
    [sym__text] = STATE(26),
    [sym_text] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_jinja_stuff_repeat1] = STATE(26),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [12] = {
    [sym__block] = STATE(12),
    [sym_for_statement] = STATE(12),
    [sym_startfor] = STATE(8),
    [sym_if_statement] = STATE(12),
    [sym_startif] = STATE(6),
    [sym_raw_statement] = STATE(12),
    [sym_startraw] = STATE(13),
    [sym_extends_statement] = STATE(12),
    [sym_block_statement] = STATE(12),
    [sym_startblock] = STATE(72),
    [sym_expression] = STATE(12),
    [sym__statement] = STATE(12),
    [sym_line_statement] = STATE(12),
    [sym_comment] = STATE(12),
    [sym__text] = STATE(26),
    [sym_text] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_jinja_stuff_repeat1] = STATE(26),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(50),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(53),
    [anon_sym_CARET_POUND] = ACTIONS(56),
    [anon_sym_LBRACE_POUND] = ACTIONS(59),
    [aux_sym__text_token1] = ACTIONS(62),
    [anon_sym_LBRACE] = ACTIONS(62),
    [anon_sym_RBRACE] = ACTIONS(62),
    [anon_sym_POUND] = ACTIONS(62),
    [anon_sym_PERCENT] = ACTIONS(62),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(67), 1,
      aux_sym__text_token1,
    STATE(84), 1,
      sym_rawtext,
    STATE(18), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(65), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [24] = 4,
    ACTIONS(71), 1,
      aux_sym__text_token1,
    STATE(105), 1,
      sym_rawtext,
    STATE(19), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(69), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [48] = 4,
    ACTIONS(71), 1,
      aux_sym__text_token1,
    STATE(102), 1,
      sym_rawtext,
    STATE(19), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(69), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [72] = 4,
    ACTIONS(67), 1,
      aux_sym__text_token1,
    STATE(86), 1,
      sym_rawtext,
    STATE(18), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(65), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [96] = 3,
    ACTIONS(76), 1,
      aux_sym__text_token1,
    STATE(17), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(73), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [117] = 4,
    ACTIONS(79), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(83), 1,
      aux_sym__text_token1,
    STATE(17), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(81), 9,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [140] = 4,
    ACTIONS(79), 1,
      anon_sym_POUND_RBRACE,
    ACTIONS(83), 1,
      aux_sym__text_token1,
    STATE(17), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(81), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [163] = 4,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    STATE(20), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(87), 5,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_POUND_POUND,
      anon_sym_LBRACE_POUND,
    ACTIONS(89), 5,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [185] = 3,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    STATE(20), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(94), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_POUND_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [205] = 2,
    STATE(23), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(94), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_POUND_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [222] = 3,
    STATE(23), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(87), 5,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_POUND_POUND,
      anon_sym_LBRACE_POUND,
    ACTIONS(96), 5,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [241] = 3,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    STATE(25), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(101), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [260] = 4,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    STATE(25), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(87), 4,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
    ACTIONS(103), 5,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [281] = 2,
    STATE(29), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(101), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [297] = 2,
    ACTIONS(108), 1,
      aux_sym__text_token1,
    ACTIONS(106), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [313] = 3,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(114), 1,
      anon_sym_POUND_POUND,
    ACTIONS(112), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [331] = 3,
    STATE(29), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(87), 4,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
    ACTIONS(116), 5,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [349] = 2,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [364] = 2,
    ACTIONS(123), 1,
      anon_sym_POUND_POUND,
    ACTIONS(112), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [379] = 2,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    ACTIONS(127), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [394] = 2,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    ACTIONS(131), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [409] = 2,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    ACTIONS(135), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [424] = 2,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(139), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [439] = 2,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    ACTIONS(143), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [454] = 2,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    ACTIONS(147), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [469] = 2,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    ACTIONS(151), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [484] = 2,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [499] = 2,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [514] = 2,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    ACTIONS(163), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [529] = 2,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
    ACTIONS(167), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [544] = 2,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    ACTIONS(171), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [559] = 2,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    ACTIONS(175), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [574] = 1,
    ACTIONS(177), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [586] = 1,
    ACTIONS(151), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [598] = 1,
    ACTIONS(155), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [610] = 1,
    ACTIONS(143), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [622] = 1,
    ACTIONS(159), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [634] = 1,
    ACTIONS(147), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [646] = 1,
    ACTIONS(179), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [658] = 1,
    ACTIONS(163), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [670] = 1,
    ACTIONS(139), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [682] = 1,
    ACTIONS(171), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [694] = 1,
    ACTIONS(175), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [706] = 1,
    ACTIONS(167), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [718] = 1,
    ACTIONS(127), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [730] = 1,
    ACTIONS(131), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [742] = 1,
    ACTIONS(121), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [754] = 1,
    ACTIONS(135), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [766] = 4,
    ACTIONS(181), 1,
      aux_sym__text_token1,
    STATE(31), 1,
      sym_jinja_stuff,
    STATE(22), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(183), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [783] = 4,
    ACTIONS(185), 1,
      aux_sym__text_token1,
    STATE(120), 1,
      sym_jinja_stuff,
    STATE(68), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(187), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [800] = 4,
    ACTIONS(101), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(189), 1,
      aux_sym__text_token1,
    STATE(64), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(191), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [817] = 4,
    ACTIONS(87), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(193), 1,
      aux_sym__text_token1,
    STATE(64), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(196), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [834] = 3,
    ACTIONS(87), 1,
      aux_sym_startfor_token1,
    STATE(65), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(199), 5,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [849] = 4,
    ACTIONS(185), 1,
      aux_sym__text_token1,
    STATE(132), 1,
      sym_jinja_stuff,
    STATE(68), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(187), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [866] = 4,
    ACTIONS(185), 1,
      aux_sym__text_token1,
    STATE(126), 1,
      sym_jinja_stuff,
    STATE(68), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(187), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [883] = 3,
    ACTIONS(94), 1,
      aux_sym_startfor_token1,
    STATE(65), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(202), 5,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [898] = 4,
    ACTIONS(185), 1,
      aux_sym__text_token1,
    STATE(112), 1,
      sym_jinja_stuff,
    STATE(68), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(187), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [915] = 4,
    ACTIONS(204), 1,
      aux_sym__text_token1,
    STATE(85), 1,
      sym_text,
    STATE(63), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(206), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [932] = 4,
    ACTIONS(208), 1,
      aux_sym__text_token1,
    STATE(28), 1,
      sym_jinja_stuff,
    STATE(21), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(210), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [949] = 4,
    ACTIONS(204), 1,
      aux_sym__text_token1,
    STATE(83), 1,
      sym_text,
    STATE(63), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(206), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [966] = 4,
    ACTIONS(185), 1,
      aux_sym__text_token1,
    STATE(119), 1,
      sym_jinja_stuff,
    STATE(68), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(187), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [983] = 4,
    ACTIONS(185), 1,
      aux_sym__text_token1,
    STATE(116), 1,
      sym_jinja_stuff,
    STATE(68), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(187), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [1000] = 4,
    ACTIONS(185), 1,
      aux_sym__text_token1,
    STATE(118), 1,
      sym_jinja_stuff,
    STATE(68), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(187), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [1017] = 6,
    ACTIONS(212), 1,
      aux_sym_startfor_token2,
    ACTIONS(214), 1,
      aux_sym_endfor_token1,
    ACTIONS(216), 1,
      aux_sym_startif_token1,
    ACTIONS(218), 1,
      aux_sym_startraw_token1,
    ACTIONS(220), 1,
      aux_sym_extends_statement_token1,
    ACTIONS(222), 1,
      aux_sym_startblock_token1,
  [1036] = 6,
    ACTIONS(212), 1,
      aux_sym_startfor_token2,
    ACTIONS(216), 1,
      aux_sym_startif_token1,
    ACTIONS(218), 1,
      aux_sym_startraw_token1,
    ACTIONS(220), 1,
      aux_sym_extends_statement_token1,
    ACTIONS(222), 1,
      aux_sym_startblock_token1,
    ACTIONS(224), 1,
      aux_sym_endif_token1,
  [1055] = 6,
    ACTIONS(212), 1,
      aux_sym_startfor_token2,
    ACTIONS(216), 1,
      aux_sym_startif_token1,
    ACTIONS(218), 1,
      aux_sym_startraw_token1,
    ACTIONS(220), 1,
      aux_sym_extends_statement_token1,
    ACTIONS(222), 1,
      aux_sym_startblock_token1,
    ACTIONS(226), 1,
      aux_sym_endif_token1,
  [1074] = 6,
    ACTIONS(212), 1,
      aux_sym_startfor_token2,
    ACTIONS(216), 1,
      aux_sym_startif_token1,
    ACTIONS(218), 1,
      aux_sym_startraw_token1,
    ACTIONS(220), 1,
      aux_sym_extends_statement_token1,
    ACTIONS(222), 1,
      aux_sym_startblock_token1,
    ACTIONS(228), 1,
      aux_sym_endfor_token1,
  [1093] = 5,
    ACTIONS(212), 1,
      aux_sym_startfor_token2,
    ACTIONS(216), 1,
      aux_sym_startif_token1,
    ACTIONS(218), 1,
      aux_sym_startraw_token1,
    ACTIONS(222), 1,
      aux_sym_startblock_token1,
    ACTIONS(230), 1,
      aux_sym_extends_statement_token1,
  [1109] = 2,
    ACTIONS(232), 1,
      aux_sym__text_token1,
    ACTIONS(234), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [1119] = 5,
    ACTIONS(212), 1,
      aux_sym_startfor_token2,
    ACTIONS(216), 1,
      aux_sym_startif_token1,
    ACTIONS(218), 1,
      aux_sym_startraw_token1,
    ACTIONS(220), 1,
      aux_sym_extends_statement_token1,
    ACTIONS(222), 1,
      aux_sym_startblock_token1,
  [1135] = 2,
    ACTIONS(236), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(55), 1,
      sym_endblock,
  [1142] = 2,
    ACTIONS(238), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(54), 1,
      sym_endraw,
  [1149] = 2,
    ACTIONS(240), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(44), 1,
      sym_endblock,
  [1156] = 2,
    ACTIONS(242), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(43), 1,
      sym_endraw,
  [1163] = 1,
    ACTIONS(244), 1,
      anon_sym_RBRACE_RBRACE,
  [1167] = 1,
    ACTIONS(246), 1,
      anon_sym_PERCENT_RBRACE,
  [1171] = 1,
    ACTIONS(248), 1,
      aux_sym_startfor_token1,
  [1175] = 1,
    ACTIONS(250), 1,
      aux_sym_startfor_token1,
  [1179] = 1,
    ACTIONS(252), 1,
      anon_sym_PERCENT_RBRACE,
  [1183] = 1,
    ACTIONS(254), 1,
      anon_sym_PERCENT_RBRACE,
  [1187] = 1,
    ACTIONS(256), 1,
      aux_sym_startfor_token1,
  [1191] = 1,
    ACTIONS(258), 1,
      anon_sym_PERCENT_RBRACE,
  [1195] = 1,
    ACTIONS(260), 1,
      anon_sym_PERCENT_RBRACE,
  [1199] = 1,
    ACTIONS(262), 1,
      anon_sym_PERCENT_RBRACE,
  [1203] = 1,
    ACTIONS(264), 1,
      anon_sym_PERCENT_RBRACE,
  [1207] = 1,
    ACTIONS(266), 1,
      aux_sym_startfor_token1,
  [1211] = 1,
    ACTIONS(268), 1,
      aux_sym_startfor_token1,
  [1215] = 1,
    ACTIONS(270), 1,
      aux_sym_endblock_token1,
  [1219] = 1,
    ACTIONS(272), 1,
      aux_sym_endraw_token1,
  [1223] = 1,
    ACTIONS(274), 1,
      anon_sym_POUND_RBRACE,
  [1227] = 1,
    ACTIONS(276), 1,
      aux_sym_startfor_token1,
  [1231] = 1,
    ACTIONS(278), 1,
      aux_sym_startfor_token1,
  [1235] = 1,
    ACTIONS(280), 1,
      anon_sym_POUND_RBRACE,
  [1239] = 1,
    ACTIONS(282), 1,
      aux_sym_startfor_token1,
  [1243] = 1,
    ACTIONS(284), 1,
      ts_builtin_sym_end,
  [1247] = 1,
    ACTIONS(286), 1,
      aux_sym_startfor_token1,
  [1251] = 1,
    ACTIONS(288), 1,
      aux_sym_startfor_token1,
  [1255] = 1,
    ACTIONS(290), 1,
      anon_sym_RBRACE_RBRACE,
  [1259] = 1,
    ACTIONS(292), 1,
      anon_sym_PERCENT_RBRACE,
  [1263] = 1,
    ACTIONS(294), 1,
      aux_sym_startfor_token1,
  [1267] = 1,
    ACTIONS(296), 1,
      anon_sym_PERCENT_RBRACE,
  [1271] = 1,
    ACTIONS(298), 1,
      anon_sym_PERCENT_RBRACE,
  [1275] = 1,
    ACTIONS(300), 1,
      anon_sym_PERCENT_RBRACE,
  [1279] = 1,
    ACTIONS(302), 1,
      aux_sym_startfor_token1,
  [1283] = 1,
    ACTIONS(304), 1,
      aux_sym_startfor_token1,
  [1287] = 1,
    ACTIONS(306), 1,
      aux_sym_startfor_token1,
  [1291] = 1,
    ACTIONS(308), 1,
      aux_sym_startfor_token1,
  [1295] = 1,
    ACTIONS(310), 1,
      aux_sym_startfor_token1,
  [1299] = 1,
    ACTIONS(312), 1,
      aux_sym_startfor_token1,
  [1303] = 1,
    ACTIONS(314), 1,
      aux_sym_startfor_token1,
  [1307] = 1,
    ACTIONS(316), 1,
      aux_sym_startfor_token1,
  [1311] = 1,
    ACTIONS(318), 1,
      aux_sym_startfor_token1,
  [1315] = 1,
    ACTIONS(320), 1,
      anon_sym_PERCENT_RBRACE,
  [1319] = 1,
    ACTIONS(322), 1,
      aux_sym_startfor_token1,
  [1323] = 1,
    ACTIONS(324), 1,
      anon_sym_PERCENT_RBRACE,
  [1327] = 1,
    ACTIONS(326), 1,
      anon_sym_PERCENT_RBRACE,
  [1331] = 1,
    ACTIONS(328), 1,
      aux_sym_endraw_token1,
  [1335] = 1,
    ACTIONS(330), 1,
      aux_sym_endblock_token1,
  [1339] = 1,
    ACTIONS(332), 1,
      aux_sym_startfor_token1,
  [1343] = 1,
    ACTIONS(334), 1,
      aux_sym_startfor_token1,
  [1347] = 1,
    ACTIONS(336), 1,
      aux_sym_startfor_token1,
  [1351] = 1,
    ACTIONS(338), 1,
      aux_sym_startfor_token1,
  [1355] = 1,
    ACTIONS(340), 1,
      aux_sym_startfor_token1,
  [1359] = 1,
    ACTIONS(342), 1,
      aux_sym_startfor_token1,
  [1363] = 1,
    ACTIONS(344), 1,
      aux_sym_startfor_token1,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 24,
  [SMALL_STATE(15)] = 48,
  [SMALL_STATE(16)] = 72,
  [SMALL_STATE(17)] = 96,
  [SMALL_STATE(18)] = 117,
  [SMALL_STATE(19)] = 140,
  [SMALL_STATE(20)] = 163,
  [SMALL_STATE(21)] = 185,
  [SMALL_STATE(22)] = 205,
  [SMALL_STATE(23)] = 222,
  [SMALL_STATE(24)] = 241,
  [SMALL_STATE(25)] = 260,
  [SMALL_STATE(26)] = 281,
  [SMALL_STATE(27)] = 297,
  [SMALL_STATE(28)] = 313,
  [SMALL_STATE(29)] = 331,
  [SMALL_STATE(30)] = 349,
  [SMALL_STATE(31)] = 364,
  [SMALL_STATE(32)] = 379,
  [SMALL_STATE(33)] = 394,
  [SMALL_STATE(34)] = 409,
  [SMALL_STATE(35)] = 424,
  [SMALL_STATE(36)] = 439,
  [SMALL_STATE(37)] = 454,
  [SMALL_STATE(38)] = 469,
  [SMALL_STATE(39)] = 484,
  [SMALL_STATE(40)] = 499,
  [SMALL_STATE(41)] = 514,
  [SMALL_STATE(42)] = 529,
  [SMALL_STATE(43)] = 544,
  [SMALL_STATE(44)] = 559,
  [SMALL_STATE(45)] = 574,
  [SMALL_STATE(46)] = 586,
  [SMALL_STATE(47)] = 598,
  [SMALL_STATE(48)] = 610,
  [SMALL_STATE(49)] = 622,
  [SMALL_STATE(50)] = 634,
  [SMALL_STATE(51)] = 646,
  [SMALL_STATE(52)] = 658,
  [SMALL_STATE(53)] = 670,
  [SMALL_STATE(54)] = 682,
  [SMALL_STATE(55)] = 694,
  [SMALL_STATE(56)] = 706,
  [SMALL_STATE(57)] = 718,
  [SMALL_STATE(58)] = 730,
  [SMALL_STATE(59)] = 742,
  [SMALL_STATE(60)] = 754,
  [SMALL_STATE(61)] = 766,
  [SMALL_STATE(62)] = 783,
  [SMALL_STATE(63)] = 800,
  [SMALL_STATE(64)] = 817,
  [SMALL_STATE(65)] = 834,
  [SMALL_STATE(66)] = 849,
  [SMALL_STATE(67)] = 866,
  [SMALL_STATE(68)] = 883,
  [SMALL_STATE(69)] = 898,
  [SMALL_STATE(70)] = 915,
  [SMALL_STATE(71)] = 932,
  [SMALL_STATE(72)] = 949,
  [SMALL_STATE(73)] = 966,
  [SMALL_STATE(74)] = 983,
  [SMALL_STATE(75)] = 1000,
  [SMALL_STATE(76)] = 1017,
  [SMALL_STATE(77)] = 1036,
  [SMALL_STATE(78)] = 1055,
  [SMALL_STATE(79)] = 1074,
  [SMALL_STATE(80)] = 1093,
  [SMALL_STATE(81)] = 1109,
  [SMALL_STATE(82)] = 1119,
  [SMALL_STATE(83)] = 1135,
  [SMALL_STATE(84)] = 1142,
  [SMALL_STATE(85)] = 1149,
  [SMALL_STATE(86)] = 1156,
  [SMALL_STATE(87)] = 1163,
  [SMALL_STATE(88)] = 1167,
  [SMALL_STATE(89)] = 1171,
  [SMALL_STATE(90)] = 1175,
  [SMALL_STATE(91)] = 1179,
  [SMALL_STATE(92)] = 1183,
  [SMALL_STATE(93)] = 1187,
  [SMALL_STATE(94)] = 1191,
  [SMALL_STATE(95)] = 1195,
  [SMALL_STATE(96)] = 1199,
  [SMALL_STATE(97)] = 1203,
  [SMALL_STATE(98)] = 1207,
  [SMALL_STATE(99)] = 1211,
  [SMALL_STATE(100)] = 1215,
  [SMALL_STATE(101)] = 1219,
  [SMALL_STATE(102)] = 1223,
  [SMALL_STATE(103)] = 1227,
  [SMALL_STATE(104)] = 1231,
  [SMALL_STATE(105)] = 1235,
  [SMALL_STATE(106)] = 1239,
  [SMALL_STATE(107)] = 1243,
  [SMALL_STATE(108)] = 1247,
  [SMALL_STATE(109)] = 1251,
  [SMALL_STATE(110)] = 1255,
  [SMALL_STATE(111)] = 1259,
  [SMALL_STATE(112)] = 1263,
  [SMALL_STATE(113)] = 1267,
  [SMALL_STATE(114)] = 1271,
  [SMALL_STATE(115)] = 1275,
  [SMALL_STATE(116)] = 1279,
  [SMALL_STATE(117)] = 1283,
  [SMALL_STATE(118)] = 1287,
  [SMALL_STATE(119)] = 1291,
  [SMALL_STATE(120)] = 1295,
  [SMALL_STATE(121)] = 1299,
  [SMALL_STATE(122)] = 1303,
  [SMALL_STATE(123)] = 1307,
  [SMALL_STATE(124)] = 1311,
  [SMALL_STATE(125)] = 1315,
  [SMALL_STATE(126)] = 1319,
  [SMALL_STATE(127)] = 1323,
  [SMALL_STATE(128)] = 1327,
  [SMALL_STATE(129)] = 1331,
  [SMALL_STATE(130)] = 1335,
  [SMALL_STATE(131)] = 1339,
  [SMALL_STATE(132)] = 1343,
  [SMALL_STATE(133)] = 1347,
  [SMALL_STATE(134)] = 1351,
  [SMALL_STATE(135)] = 1355,
  [SMALL_STATE(136)] = 1359,
  [SMALL_STATE(137)] = 1363,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(134),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(93),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(117),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(71),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(24),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(137),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(131),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(61),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(14),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(26),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rawtext_repeat1, 2), SHIFT_REPEAT(17),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rawtext_repeat1, 2), SHIFT_REPEAT(17),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rawtext, 1),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2), SHIFT_REPEAT(20),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jinja_stuff, 1),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jinja_stuff, 1),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2), SHIFT_REPEAT(23),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2), SHIFT_REPEAT(25),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_startraw, 5),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_startraw, 5),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_statement, 2),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_statement, 2),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2), SHIFT_REPEAT(29),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_endif, 5),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_endif, 5),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_endblock, 5),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_endblock, 5),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_endraw, 5),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_endraw, 5),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_endfor, 5),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_endfor, 5),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_statement, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_statement, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 2),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends_statement, 6),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extends_statement, 6),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 3),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 3),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 2),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 2),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 5),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 5),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_statement, 3),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_statement, 3),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 3),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 3),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_startif, 6),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_startfor, 6),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2), SHIFT_REPEAT(64),
  [196] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2), SHIFT_REPEAT(64),
  [199] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2), SHIFT_REPEAT(65),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_startblock, 6),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_startblock, 6),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [284] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_jinja2(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
