#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 106
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  anon_sym_LBRACE_PERCENT = 1,
  aux_sym_startfor_token1 = 2,
  aux_sym_startfor_token2 = 3,
  anon_sym_PERCENT_RBRACE = 4,
  aux_sym_endfor_token1 = 5,
  aux_sym_startif_token1 = 6,
  aux_sym_endif_token1 = 7,
  aux_sym_startraw_token1 = 8,
  aux_sym_endraw_token1 = 9,
  anon_sym_LBRACE_LBRACE = 10,
  anon_sym_RBRACE_RBRACE = 11,
  anon_sym_CARET_POUND = 12,
  anon_sym_POUND_POUND = 13,
  anon_sym_LBRACE_POUND = 14,
  anon_sym_POUND_RBRACE = 15,
  aux_sym__text_token1 = 16,
  anon_sym_LBRACE = 17,
  anon_sym_RBRACE = 18,
  anon_sym_POUND = 19,
  anon_sym_PERCENT = 20,
  sym_source_file = 21,
  sym__block = 22,
  sym_for_statement = 23,
  sym_startfor = 24,
  sym_endfor = 25,
  sym_if_statement = 26,
  sym_startif = 27,
  sym_endif = 28,
  sym_raw_statement = 29,
  sym_startraw = 30,
  sym_endraw = 31,
  sym_expression = 32,
  sym__statement = 33,
  sym_line_statement = 34,
  sym_comment = 35,
  sym__text = 36,
  sym__rawtext = 37,
  sym_jinja_stuff = 38,
  sym_text = 39,
  sym_rawtext = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_jinja_stuff_repeat1 = 42,
  aux_sym_rawtext_repeat1 = 43,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [aux_sym_startfor_token1] = "startfor_token1",
  [aux_sym_startfor_token2] = "startfor_token2",
  [anon_sym_PERCENT_RBRACE] = "%}",
  [aux_sym_endfor_token1] = "endfor_token1",
  [aux_sym_startif_token1] = "startif_token1",
  [aux_sym_endif_token1] = "endif_token1",
  [aux_sym_startraw_token1] = "startraw_token1",
  [aux_sym_endraw_token1] = "endraw_token1",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_CARET_POUND] = "^#",
  [anon_sym_POUND_POUND] = "##",
  [anon_sym_LBRACE_POUND] = "{#",
  [anon_sym_POUND_RBRACE] = "#}",
  [aux_sym__text_token1] = "_text_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_POUND] = "#",
  [anon_sym_PERCENT] = "%",
  [sym_source_file] = "source_file",
  [sym__block] = "_block",
  [sym_for_statement] = "for_statement",
  [sym_startfor] = "startfor",
  [sym_endfor] = "endfor",
  [sym_if_statement] = "if_statement",
  [sym_startif] = "startif",
  [sym_endif] = "endif",
  [sym_raw_statement] = "raw_statement",
  [sym_startraw] = "startraw",
  [sym_endraw] = "endraw",
  [sym_expression] = "expression",
  [sym__statement] = "_statement",
  [sym_line_statement] = "line_statement",
  [sym_comment] = "comment",
  [sym__text] = "_text",
  [sym__rawtext] = "_rawtext",
  [sym_jinja_stuff] = "jinja_stuff",
  [sym_text] = "text",
  [sym_rawtext] = "rawtext",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_jinja_stuff_repeat1] = "jinja_stuff_repeat1",
  [aux_sym_rawtext_repeat1] = "rawtext_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [aux_sym_startfor_token1] = aux_sym_startfor_token1,
  [aux_sym_startfor_token2] = aux_sym_startfor_token2,
  [anon_sym_PERCENT_RBRACE] = anon_sym_PERCENT_RBRACE,
  [aux_sym_endfor_token1] = aux_sym_endfor_token1,
  [aux_sym_startif_token1] = aux_sym_startif_token1,
  [aux_sym_endif_token1] = aux_sym_endif_token1,
  [aux_sym_startraw_token1] = aux_sym_startraw_token1,
  [aux_sym_endraw_token1] = aux_sym_endraw_token1,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_CARET_POUND] = anon_sym_CARET_POUND,
  [anon_sym_POUND_POUND] = anon_sym_POUND_POUND,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [anon_sym_POUND_RBRACE] = anon_sym_POUND_RBRACE,
  [aux_sym__text_token1] = aux_sym__text_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_source_file] = sym_source_file,
  [sym__block] = sym__block,
  [sym_for_statement] = sym_for_statement,
  [sym_startfor] = sym_startfor,
  [sym_endfor] = sym_endfor,
  [sym_if_statement] = sym_if_statement,
  [sym_startif] = sym_startif,
  [sym_endif] = sym_endif,
  [sym_raw_statement] = sym_raw_statement,
  [sym_startraw] = sym_startraw,
  [sym_endraw] = sym_endraw,
  [sym_expression] = sym_expression,
  [sym__statement] = sym__statement,
  [sym_line_statement] = sym_line_statement,
  [sym_comment] = sym_comment,
  [sym__text] = sym__text,
  [sym__rawtext] = sym__rawtext,
  [sym_jinja_stuff] = sym_jinja_stuff,
  [sym_text] = sym_text,
  [sym_rawtext] = sym_rawtext,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_jinja_stuff_repeat1] = aux_sym_jinja_stuff_repeat1,
  [aux_sym_rawtext_repeat1] = aux_sym_rawtext_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_startfor_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_startfor_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_endfor_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_startif_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_endif_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_startraw_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_endraw_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_for_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_startfor] = {
    .visible = true,
    .named = true,
  },
  [sym_endfor] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_startif] = {
    .visible = true,
    .named = true,
  },
  [sym_endif] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_startraw] = {
    .visible = true,
    .named = true,
  },
  [sym_endraw] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_line_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__text] = {
    .visible = false,
    .named = true,
  },
  [sym__rawtext] = {
    .visible = false,
    .named = true,
  },
  [sym_jinja_stuff] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_rawtext] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_jinja_stuff_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rawtext_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[1][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      if (lookahead == '#') ADVANCE(51);
      if (lookahead == '%') ADVANCE(54);
      if (lookahead == '^') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(11);
      if (lookahead == 'f') ADVANCE(12);
      if (lookahead == 'i') ADVANCE(8);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == '{') ADVANCE(46);
      if (lookahead == '}') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(51);
      if (lookahead == '%') ADVANCE(54);
      if (lookahead == '^') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(11);
      if (lookahead == 'f') ADVANCE(12);
      if (lookahead == 'i') ADVANCE(8);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == '{') ADVANCE(46);
      if (lookahead == '}') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(49);
      if (lookahead == '%') ADVANCE(53);
      if (lookahead == '{') ADVANCE(45);
      if (lookahead == '}') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(52);
      if (lookahead == '%') ADVANCE(54);
      if (lookahead == '{') ADVANCE(46);
      if (lookahead == '}') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == 'f') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(13);
      if (lookahead == 'i') ADVANCE(9);
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead == 'w') ADVANCE(33);
      END_STATE();
    case 17:
      if (lookahead == 'w') ADVANCE(34);
      END_STATE();
    case 18:
      if (eof) ADVANCE(20);
      if (lookahead == '#') ADVANCE(49);
      if (lookahead == '%') ADVANCE(53);
      if (lookahead == '^') ADVANCE(41);
      if (lookahead == '{') ADVANCE(46);
      if (lookahead == '}') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '#') ADVANCE(50);
      if (lookahead == '%') ADVANCE(53);
      if (lookahead == '^') ADVANCE(41);
      if (lookahead == '{') ADVANCE(46);
      if (lookahead == '}') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_startfor_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_startfor_token1);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_startfor_token1);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_startfor_token1);
      if (lookahead == '+') ADVANCE(22);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_startfor_token1);
      if (lookahead == '+') ADVANCE(22);
      if (lookahead == '-') ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_startfor_token1);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_startfor_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_endfor_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_startif_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_endif_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_startraw_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_endraw_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_CARET_POUND);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_POUND_POUND);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_POUND_RBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == '#') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == '^') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym__text_token1);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(39);
      if (lookahead == '%') ADVANCE(21);
      if (lookahead == '{') ADVANCE(35);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '}') ADVANCE(36);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(38);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '}') ADVANCE(40);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '}') ADVANCE(40);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '}') ADVANCE(29);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 18},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 18},
  [7] = {.lex_state = 18},
  [8] = {.lex_state = 18},
  [9] = {.lex_state = 18},
  [10] = {.lex_state = 18},
  [11] = {.lex_state = 18},
  [12] = {.lex_state = 18},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 19},
  [21] = {.lex_state = 19},
  [22] = {.lex_state = 18},
  [23] = {.lex_state = 18},
  [24] = {.lex_state = 19},
  [25] = {.lex_state = 19},
  [26] = {.lex_state = 18},
  [27] = {.lex_state = 19},
  [28] = {.lex_state = 18},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 18},
  [31] = {.lex_state = 18},
  [32] = {.lex_state = 18},
  [33] = {.lex_state = 18},
  [34] = {.lex_state = 18},
  [35] = {.lex_state = 19},
  [36] = {.lex_state = 18},
  [37] = {.lex_state = 18},
  [38] = {.lex_state = 18},
  [39] = {.lex_state = 18},
  [40] = {.lex_state = 18},
  [41] = {.lex_state = 18},
  [42] = {.lex_state = 18},
  [43] = {.lex_state = 18},
  [44] = {.lex_state = 18},
  [45] = {.lex_state = 18},
  [46] = {.lex_state = 18},
  [47] = {.lex_state = 18},
  [48] = {.lex_state = 18},
  [49] = {.lex_state = 18},
  [50] = {.lex_state = 18},
  [51] = {.lex_state = 18},
  [52] = {.lex_state = 18},
  [53] = {.lex_state = 18},
  [54] = {.lex_state = 18},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 23},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 23},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 26},
  [73] = {.lex_state = 26},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 26},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 26},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 26},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 26},
  [89] = {.lex_state = 26},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 26},
  [93] = {.lex_state = 26},
  [94] = {.lex_state = 26},
  [95] = {.lex_state = 26},
  [96] = {.lex_state = 26},
  [97] = {.lex_state = 26},
  [98] = {.lex_state = 26},
  [99] = {.lex_state = 26},
  [100] = {.lex_state = 26},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 26},
  [103] = {.lex_state = 26},
  [104] = {.lex_state = 26},
  [105] = {.lex_state = 26},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
    [aux_sym_startfor_token2] = ACTIONS(1),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(1),
    [aux_sym_endfor_token1] = ACTIONS(1),
    [aux_sym_startif_token1] = ACTIONS(1),
    [aux_sym_endif_token1] = ACTIONS(1),
    [aux_sym_startraw_token1] = ACTIONS(1),
    [aux_sym_endraw_token1] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_CARET_POUND] = ACTIONS(1),
    [anon_sym_POUND_POUND] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_POUND_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(70),
    [sym__block] = STATE(7),
    [sym_for_statement] = STATE(7),
    [sym_startfor] = STATE(5),
    [sym_if_statement] = STATE(7),
    [sym_startif] = STATE(6),
    [sym_raw_statement] = STATE(7),
    [sym_startraw] = STATE(14),
    [sym_expression] = STATE(7),
    [sym__statement] = STATE(7),
    [sym_line_statement] = STATE(7),
    [sym_comment] = STATE(7),
    [sym__text] = STATE(22),
    [sym_text] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_jinja_stuff_repeat1] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_CARET_POUND] = ACTIONS(9),
    [anon_sym_LBRACE_POUND] = ACTIONS(11),
    [aux_sym__text_token1] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
  },
  [2] = {
    [sym__block] = STATE(3),
    [sym_for_statement] = STATE(3),
    [sym_startfor] = STATE(8),
    [sym_if_statement] = STATE(3),
    [sym_startif] = STATE(2),
    [sym_endif] = STATE(48),
    [sym_raw_statement] = STATE(3),
    [sym_startraw] = STATE(16),
    [sym_expression] = STATE(3),
    [sym__statement] = STATE(3),
    [sym_line_statement] = STATE(3),
    [sym_comment] = STATE(3),
    [sym__text] = STATE(28),
    [sym_text] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_jinja_stuff_repeat1] = STATE(28),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(15),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [3] = {
    [sym__block] = STATE(12),
    [sym_for_statement] = STATE(12),
    [sym_startfor] = STATE(8),
    [sym_if_statement] = STATE(12),
    [sym_startif] = STATE(2),
    [sym_endif] = STATE(53),
    [sym_raw_statement] = STATE(12),
    [sym_startraw] = STATE(16),
    [sym_expression] = STATE(12),
    [sym__statement] = STATE(12),
    [sym_line_statement] = STATE(12),
    [sym_comment] = STATE(12),
    [sym__text] = STATE(28),
    [sym_text] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_jinja_stuff_repeat1] = STATE(28),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(15),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [4] = {
    [sym__block] = STATE(12),
    [sym_for_statement] = STATE(12),
    [sym_startfor] = STATE(8),
    [sym_endfor] = STATE(42),
    [sym_if_statement] = STATE(12),
    [sym_startif] = STATE(2),
    [sym_raw_statement] = STATE(12),
    [sym_startraw] = STATE(16),
    [sym_expression] = STATE(12),
    [sym__statement] = STATE(12),
    [sym_line_statement] = STATE(12),
    [sym_comment] = STATE(12),
    [sym__text] = STATE(28),
    [sym_text] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_jinja_stuff_repeat1] = STATE(28),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [5] = {
    [sym__block] = STATE(11),
    [sym_for_statement] = STATE(11),
    [sym_startfor] = STATE(8),
    [sym_endfor] = STATE(31),
    [sym_if_statement] = STATE(11),
    [sym_startif] = STATE(2),
    [sym_raw_statement] = STATE(11),
    [sym_startraw] = STATE(16),
    [sym_expression] = STATE(11),
    [sym__statement] = STATE(11),
    [sym_line_statement] = STATE(11),
    [sym_comment] = STATE(11),
    [sym__text] = STATE(28),
    [sym_text] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_jinja_stuff_repeat1] = STATE(28),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [6] = {
    [sym__block] = STATE(9),
    [sym_for_statement] = STATE(9),
    [sym_startfor] = STATE(8),
    [sym_if_statement] = STATE(9),
    [sym_startif] = STATE(2),
    [sym_endif] = STATE(32),
    [sym_raw_statement] = STATE(9),
    [sym_startraw] = STATE(16),
    [sym_expression] = STATE(9),
    [sym__statement] = STATE(9),
    [sym_line_statement] = STATE(9),
    [sym_comment] = STATE(9),
    [sym__text] = STATE(28),
    [sym_text] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_jinja_stuff_repeat1] = STATE(28),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [7] = {
    [sym__block] = STATE(10),
    [sym_for_statement] = STATE(10),
    [sym_startfor] = STATE(5),
    [sym_if_statement] = STATE(10),
    [sym_startif] = STATE(6),
    [sym_raw_statement] = STATE(10),
    [sym_startraw] = STATE(14),
    [sym_expression] = STATE(10),
    [sym__statement] = STATE(10),
    [sym_line_statement] = STATE(10),
    [sym_comment] = STATE(10),
    [sym__text] = STATE(22),
    [sym_text] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [aux_sym_jinja_stuff_repeat1] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_CARET_POUND] = ACTIONS(9),
    [anon_sym_LBRACE_POUND] = ACTIONS(11),
    [aux_sym__text_token1] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(13),
  },
  [8] = {
    [sym__block] = STATE(4),
    [sym_for_statement] = STATE(4),
    [sym_startfor] = STATE(8),
    [sym_endfor] = STATE(45),
    [sym_if_statement] = STATE(4),
    [sym_startif] = STATE(2),
    [sym_raw_statement] = STATE(4),
    [sym_startraw] = STATE(16),
    [sym_expression] = STATE(4),
    [sym__statement] = STATE(4),
    [sym_line_statement] = STATE(4),
    [sym_comment] = STATE(4),
    [sym__text] = STATE(28),
    [sym_text] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_jinja_stuff_repeat1] = STATE(28),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [9] = {
    [sym__block] = STATE(12),
    [sym_for_statement] = STATE(12),
    [sym_startfor] = STATE(8),
    [sym_if_statement] = STATE(12),
    [sym_startif] = STATE(2),
    [sym_endif] = STATE(38),
    [sym_raw_statement] = STATE(12),
    [sym_startraw] = STATE(16),
    [sym_expression] = STATE(12),
    [sym__statement] = STATE(12),
    [sym_line_statement] = STATE(12),
    [sym_comment] = STATE(12),
    [sym__text] = STATE(28),
    [sym_text] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_jinja_stuff_repeat1] = STATE(28),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [10] = {
    [sym__block] = STATE(10),
    [sym_for_statement] = STATE(10),
    [sym_startfor] = STATE(5),
    [sym_if_statement] = STATE(10),
    [sym_startif] = STATE(6),
    [sym_raw_statement] = STATE(10),
    [sym_startraw] = STATE(14),
    [sym_expression] = STATE(10),
    [sym__statement] = STATE(10),
    [sym_line_statement] = STATE(10),
    [sym_comment] = STATE(10),
    [sym__text] = STATE(22),
    [sym_text] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [aux_sym_jinja_stuff_repeat1] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(33),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(35),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(38),
    [anon_sym_CARET_POUND] = ACTIONS(41),
    [anon_sym_LBRACE_POUND] = ACTIONS(44),
    [aux_sym__text_token1] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(47),
    [anon_sym_RBRACE] = ACTIONS(47),
    [anon_sym_POUND] = ACTIONS(47),
    [anon_sym_PERCENT] = ACTIONS(47),
  },
  [11] = {
    [sym__block] = STATE(12),
    [sym_for_statement] = STATE(12),
    [sym_startfor] = STATE(8),
    [sym_endfor] = STATE(36),
    [sym_if_statement] = STATE(12),
    [sym_startif] = STATE(2),
    [sym_raw_statement] = STATE(12),
    [sym_startraw] = STATE(16),
    [sym_expression] = STATE(12),
    [sym__statement] = STATE(12),
    [sym_line_statement] = STATE(12),
    [sym_comment] = STATE(12),
    [sym__text] = STATE(28),
    [sym_text] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_jinja_stuff_repeat1] = STATE(28),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(17),
    [anon_sym_CARET_POUND] = ACTIONS(19),
    [anon_sym_LBRACE_POUND] = ACTIONS(21),
    [aux_sym__text_token1] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_POUND] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
  },
  [12] = {
    [sym__block] = STATE(12),
    [sym_for_statement] = STATE(12),
    [sym_startfor] = STATE(8),
    [sym_if_statement] = STATE(12),
    [sym_startif] = STATE(2),
    [sym_raw_statement] = STATE(12),
    [sym_startraw] = STATE(16),
    [sym_expression] = STATE(12),
    [sym__statement] = STATE(12),
    [sym_line_statement] = STATE(12),
    [sym_comment] = STATE(12),
    [sym__text] = STATE(28),
    [sym_text] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_jinja_stuff_repeat1] = STATE(28),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(35),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(50),
    [anon_sym_CARET_POUND] = ACTIONS(53),
    [anon_sym_LBRACE_POUND] = ACTIONS(56),
    [aux_sym__text_token1] = ACTIONS(59),
    [anon_sym_LBRACE] = ACTIONS(59),
    [anon_sym_RBRACE] = ACTIONS(59),
    [anon_sym_POUND] = ACTIONS(59),
    [anon_sym_PERCENT] = ACTIONS(59),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(64), 1,
      aux_sym__text_token1,
    STATE(80), 1,
      sym_rawtext,
    STATE(18), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(62), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [24] = 4,
    ACTIONS(68), 1,
      aux_sym__text_token1,
    STATE(68), 1,
      sym_rawtext,
    STATE(17), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(66), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [48] = 4,
    ACTIONS(64), 1,
      aux_sym__text_token1,
    STATE(84), 1,
      sym_rawtext,
    STATE(18), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(62), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [72] = 4,
    ACTIONS(68), 1,
      aux_sym__text_token1,
    STATE(69), 1,
      sym_rawtext,
    STATE(17), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(66), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [96] = 4,
    ACTIONS(70), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(74), 1,
      aux_sym__text_token1,
    STATE(19), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(72), 9,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [119] = 4,
    ACTIONS(70), 1,
      anon_sym_POUND_RBRACE,
    ACTIONS(74), 1,
      aux_sym__text_token1,
    STATE(19), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(72), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [142] = 3,
    ACTIONS(79), 1,
      aux_sym__text_token1,
    STATE(19), 3,
      sym__text,
      sym__rawtext,
      aux_sym_rawtext_repeat1,
    ACTIONS(76), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [163] = 4,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    STATE(20), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(84), 5,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_POUND_POUND,
      anon_sym_LBRACE_POUND,
    ACTIONS(86), 5,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [185] = 3,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    STATE(20), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(91), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_POUND_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [205] = 3,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    STATE(23), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(95), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [224] = 4,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    STATE(23), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(84), 4,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
    ACTIONS(97), 5,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [245] = 2,
    STATE(25), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(91), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_POUND_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [262] = 3,
    STATE(25), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(84), 5,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_POUND_POUND,
      anon_sym_LBRACE_POUND,
    ACTIONS(100), 5,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [281] = 3,
    STATE(26), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(84), 4,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
    ACTIONS(103), 5,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [299] = 3,
    ACTIONS(106), 1,
      ts_builtin_sym_end,
    ACTIONS(110), 1,
      anon_sym_POUND_POUND,
    ACTIONS(108), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [317] = 2,
    STATE(26), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(95), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [333] = 2,
    ACTIONS(114), 1,
      aux_sym__text_token1,
    ACTIONS(112), 10,
      anon_sym_LBRACE_PERCENT,
      anon_sym_PERCENT_RBRACE,
      anon_sym_LBRACE_LBRACE,
      anon_sym_RBRACE_RBRACE,
      anon_sym_LBRACE_POUND,
      anon_sym_POUND_RBRACE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [349] = 2,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    ACTIONS(118), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [364] = 2,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    ACTIONS(122), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [379] = 2,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    ACTIONS(126), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [394] = 2,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    ACTIONS(130), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [409] = 2,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
    ACTIONS(134), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [424] = 2,
    ACTIONS(136), 1,
      anon_sym_POUND_POUND,
    ACTIONS(108), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [439] = 2,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    ACTIONS(140), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [454] = 2,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    ACTIONS(144), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [469] = 2,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    ACTIONS(148), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [484] = 2,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(152), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [499] = 2,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [514] = 2,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    ACTIONS(160), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [529] = 1,
    ACTIONS(140), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [541] = 1,
    ACTIONS(162), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [553] = 1,
    ACTIONS(160), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [565] = 1,
    ACTIONS(122), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [577] = 1,
    ACTIONS(144), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [589] = 1,
    ACTIONS(118), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [601] = 1,
    ACTIONS(126), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [613] = 1,
    ACTIONS(134), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [625] = 1,
    ACTIONS(130), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [637] = 1,
    ACTIONS(152), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [649] = 1,
    ACTIONS(156), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [661] = 1,
    ACTIONS(148), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [673] = 1,
    ACTIONS(164), 9,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_CARET_POUND,
      anon_sym_LBRACE_POUND,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [685] = 4,
    ACTIONS(166), 1,
      aux_sym__text_token1,
    STATE(35), 1,
      sym_jinja_stuff,
    STATE(24), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(168), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [702] = 4,
    ACTIONS(170), 1,
      aux_sym__text_token1,
    STATE(27), 1,
      sym_jinja_stuff,
    STATE(21), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(172), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [719] = 4,
    ACTIONS(174), 1,
      aux_sym__text_token1,
    STATE(94), 1,
      sym_jinja_stuff,
    STATE(59), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(176), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [736] = 4,
    ACTIONS(174), 1,
      aux_sym__text_token1,
    STATE(92), 1,
      sym_jinja_stuff,
    STATE(59), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(176), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [753] = 3,
    ACTIONS(91), 1,
      aux_sym_startfor_token1,
    STATE(62), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(178), 5,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [768] = 4,
    ACTIONS(174), 1,
      aux_sym__text_token1,
    STATE(98), 1,
      sym_jinja_stuff,
    STATE(59), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(176), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [785] = 4,
    ACTIONS(174), 1,
      aux_sym__text_token1,
    STATE(100), 1,
      sym_jinja_stuff,
    STATE(59), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(176), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [802] = 3,
    ACTIONS(84), 1,
      aux_sym_startfor_token1,
    STATE(62), 2,
      sym__text,
      aux_sym_jinja_stuff_repeat1,
    ACTIONS(180), 5,
      aux_sym__text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_POUND,
      anon_sym_PERCENT,
  [817] = 4,
    ACTIONS(183), 1,
      aux_sym_startfor_token2,
    ACTIONS(185), 1,
      aux_sym_endfor_token1,
    ACTIONS(187), 1,
      aux_sym_startif_token1,
    ACTIONS(189), 1,
      aux_sym_startraw_token1,
  [830] = 4,
    ACTIONS(183), 1,
      aux_sym_startfor_token2,
    ACTIONS(187), 1,
      aux_sym_startif_token1,
    ACTIONS(189), 1,
      aux_sym_startraw_token1,
    ACTIONS(191), 1,
      aux_sym_endif_token1,
  [843] = 4,
    ACTIONS(183), 1,
      aux_sym_startfor_token2,
    ACTIONS(187), 1,
      aux_sym_startif_token1,
    ACTIONS(189), 1,
      aux_sym_startraw_token1,
    ACTIONS(193), 1,
      aux_sym_endif_token1,
  [856] = 4,
    ACTIONS(183), 1,
      aux_sym_startfor_token2,
    ACTIONS(187), 1,
      aux_sym_startif_token1,
    ACTIONS(189), 1,
      aux_sym_startraw_token1,
    ACTIONS(195), 1,
      aux_sym_endfor_token1,
  [869] = 3,
    ACTIONS(183), 1,
      aux_sym_startfor_token2,
    ACTIONS(187), 1,
      aux_sym_startif_token1,
    ACTIONS(189), 1,
      aux_sym_startraw_token1,
  [879] = 2,
    ACTIONS(197), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(40), 1,
      sym_endraw,
  [886] = 2,
    ACTIONS(199), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(52), 1,
      sym_endraw,
  [893] = 1,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
  [897] = 1,
    ACTIONS(203), 1,
      anon_sym_PERCENT_RBRACE,
  [901] = 1,
    ACTIONS(205), 1,
      aux_sym_startfor_token1,
  [905] = 1,
    ACTIONS(207), 1,
      aux_sym_startfor_token1,
  [909] = 1,
    ACTIONS(209), 1,
      anon_sym_PERCENT_RBRACE,
  [913] = 1,
    ACTIONS(211), 1,
      anon_sym_PERCENT_RBRACE,
  [917] = 1,
    ACTIONS(213), 1,
      anon_sym_PERCENT_RBRACE,
  [921] = 1,
    ACTIONS(215), 1,
      aux_sym_endraw_token1,
  [925] = 1,
    ACTIONS(217), 1,
      anon_sym_RBRACE_RBRACE,
  [929] = 1,
    ACTIONS(219), 1,
      aux_sym_startfor_token1,
  [933] = 1,
    ACTIONS(221), 1,
      anon_sym_POUND_RBRACE,
  [937] = 1,
    ACTIONS(223), 1,
      aux_sym_startfor_token1,
  [941] = 1,
    ACTIONS(225), 1,
      anon_sym_RBRACE_RBRACE,
  [945] = 1,
    ACTIONS(227), 1,
      anon_sym_PERCENT_RBRACE,
  [949] = 1,
    ACTIONS(229), 1,
      anon_sym_POUND_RBRACE,
  [953] = 1,
    ACTIONS(231), 1,
      aux_sym_startfor_token1,
  [957] = 1,
    ACTIONS(233), 1,
      anon_sym_PERCENT_RBRACE,
  [961] = 1,
    ACTIONS(235), 1,
      anon_sym_PERCENT_RBRACE,
  [965] = 1,
    ACTIONS(237), 1,
      aux_sym_startfor_token1,
  [969] = 1,
    ACTIONS(239), 1,
      aux_sym_startfor_token1,
  [973] = 1,
    ACTIONS(241), 1,
      anon_sym_PERCENT_RBRACE,
  [977] = 1,
    ACTIONS(243), 1,
      anon_sym_PERCENT_RBRACE,
  [981] = 1,
    ACTIONS(245), 1,
      aux_sym_startfor_token1,
  [985] = 1,
    ACTIONS(247), 1,
      aux_sym_startfor_token1,
  [989] = 1,
    ACTIONS(249), 1,
      aux_sym_startfor_token1,
  [993] = 1,
    ACTIONS(251), 1,
      aux_sym_startfor_token1,
  [997] = 1,
    ACTIONS(253), 1,
      aux_sym_startfor_token1,
  [1001] = 1,
    ACTIONS(255), 1,
      aux_sym_startfor_token1,
  [1005] = 1,
    ACTIONS(257), 1,
      aux_sym_startfor_token1,
  [1009] = 1,
    ACTIONS(259), 1,
      aux_sym_startfor_token1,
  [1013] = 1,
    ACTIONS(261), 1,
      aux_sym_startfor_token1,
  [1017] = 1,
    ACTIONS(263), 1,
      aux_sym_endraw_token1,
  [1021] = 1,
    ACTIONS(265), 1,
      aux_sym_startfor_token1,
  [1025] = 1,
    ACTIONS(267), 1,
      aux_sym_startfor_token1,
  [1029] = 1,
    ACTIONS(269), 1,
      aux_sym_startfor_token1,
  [1033] = 1,
    ACTIONS(271), 1,
      aux_sym_startfor_token1,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 24,
  [SMALL_STATE(15)] = 48,
  [SMALL_STATE(16)] = 72,
  [SMALL_STATE(17)] = 96,
  [SMALL_STATE(18)] = 119,
  [SMALL_STATE(19)] = 142,
  [SMALL_STATE(20)] = 163,
  [SMALL_STATE(21)] = 185,
  [SMALL_STATE(22)] = 205,
  [SMALL_STATE(23)] = 224,
  [SMALL_STATE(24)] = 245,
  [SMALL_STATE(25)] = 262,
  [SMALL_STATE(26)] = 281,
  [SMALL_STATE(27)] = 299,
  [SMALL_STATE(28)] = 317,
  [SMALL_STATE(29)] = 333,
  [SMALL_STATE(30)] = 349,
  [SMALL_STATE(31)] = 364,
  [SMALL_STATE(32)] = 379,
  [SMALL_STATE(33)] = 394,
  [SMALL_STATE(34)] = 409,
  [SMALL_STATE(35)] = 424,
  [SMALL_STATE(36)] = 439,
  [SMALL_STATE(37)] = 454,
  [SMALL_STATE(38)] = 469,
  [SMALL_STATE(39)] = 484,
  [SMALL_STATE(40)] = 499,
  [SMALL_STATE(41)] = 514,
  [SMALL_STATE(42)] = 529,
  [SMALL_STATE(43)] = 541,
  [SMALL_STATE(44)] = 553,
  [SMALL_STATE(45)] = 565,
  [SMALL_STATE(46)] = 577,
  [SMALL_STATE(47)] = 589,
  [SMALL_STATE(48)] = 601,
  [SMALL_STATE(49)] = 613,
  [SMALL_STATE(50)] = 625,
  [SMALL_STATE(51)] = 637,
  [SMALL_STATE(52)] = 649,
  [SMALL_STATE(53)] = 661,
  [SMALL_STATE(54)] = 673,
  [SMALL_STATE(55)] = 685,
  [SMALL_STATE(56)] = 702,
  [SMALL_STATE(57)] = 719,
  [SMALL_STATE(58)] = 736,
  [SMALL_STATE(59)] = 753,
  [SMALL_STATE(60)] = 768,
  [SMALL_STATE(61)] = 785,
  [SMALL_STATE(62)] = 802,
  [SMALL_STATE(63)] = 817,
  [SMALL_STATE(64)] = 830,
  [SMALL_STATE(65)] = 843,
  [SMALL_STATE(66)] = 856,
  [SMALL_STATE(67)] = 869,
  [SMALL_STATE(68)] = 879,
  [SMALL_STATE(69)] = 886,
  [SMALL_STATE(70)] = 893,
  [SMALL_STATE(71)] = 897,
  [SMALL_STATE(72)] = 901,
  [SMALL_STATE(73)] = 905,
  [SMALL_STATE(74)] = 909,
  [SMALL_STATE(75)] = 913,
  [SMALL_STATE(76)] = 917,
  [SMALL_STATE(77)] = 921,
  [SMALL_STATE(78)] = 925,
  [SMALL_STATE(79)] = 929,
  [SMALL_STATE(80)] = 933,
  [SMALL_STATE(81)] = 937,
  [SMALL_STATE(82)] = 941,
  [SMALL_STATE(83)] = 945,
  [SMALL_STATE(84)] = 949,
  [SMALL_STATE(85)] = 953,
  [SMALL_STATE(86)] = 957,
  [SMALL_STATE(87)] = 961,
  [SMALL_STATE(88)] = 965,
  [SMALL_STATE(89)] = 969,
  [SMALL_STATE(90)] = 973,
  [SMALL_STATE(91)] = 977,
  [SMALL_STATE(92)] = 981,
  [SMALL_STATE(93)] = 985,
  [SMALL_STATE(94)] = 989,
  [SMALL_STATE(95)] = 993,
  [SMALL_STATE(96)] = 997,
  [SMALL_STATE(97)] = 1001,
  [SMALL_STATE(98)] = 1005,
  [SMALL_STATE(99)] = 1009,
  [SMALL_STATE(100)] = 1013,
  [SMALL_STATE(101)] = 1017,
  [SMALL_STATE(102)] = 1021,
  [SMALL_STATE(103)] = 1025,
  [SMALL_STATE(104)] = 1029,
  [SMALL_STATE(105)] = 1033,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(89),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(93),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(56),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(13),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(22),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(102),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(55),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(28),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rawtext, 1),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rawtext_repeat1, 2), SHIFT_REPEAT(19),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rawtext_repeat1, 2), SHIFT_REPEAT(19),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2), SHIFT_REPEAT(20),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jinja_stuff, 1),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jinja_stuff, 1),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_text, 1),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2), SHIFT_REPEAT(23),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2), SHIFT_REPEAT(25),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2), SHIFT_REPEAT(26),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_statement, 2),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_statement, 2),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_startraw, 5),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_startraw, 5),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_endif, 5),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_endif, 5),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 2),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 2),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 2),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 2),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_statement, 3),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_statement, 3),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_statement, 3),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_statement, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_endraw, 5),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_endraw, 5),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 5),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 5),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_statement, 3),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_statement, 3),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_endfor, 5),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_endfor, 5),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_startif, 6),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_startfor, 6),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [180] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_stuff_repeat1, 2), SHIFT_REPEAT(62),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [201] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_jinja2(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
